### ISSUE TITLE
recent releases are missing in bazel central registry

### ISSUE THREAD

**Issue by chulkilee** [GoogleContainerTools/rules_distroless#77]
As of 2024-08-17

- github: 0.3.6
- bazel central registry: 0.3.3

- https://registry.bazel.build/modules/rules_distroless
- https://github.com/GoogleContainerTools/rules_distroless/issues/37#issuecomment-2284203498

**Comment by chulkilee** [comment]
@loopingz @loopingz @thesayyn  could you take a look on those PRs?

For others trying to use the latest version:

```bazel
bazel_dep(name = "rules_distroless", version = "0.3.6")

git_override(
    module_name = "rules_distroless",
    commit = "feae484ebb4d28d44bbc4fbf5143b89c8de7331b", # 0.3.6
    remote = "https://github.com/GoogleContainerTools/rules_distroless",
)
```

**Comment by thesayyn** [comment]
fixed https://github.com/bazelbuild/bazel-central-registry/pull/2730

**Comment by chulkilee** [comment]
@thesayyn  Can we close this issue once it's actually released to the registry? https://registry.bazel.build/modules/rules_distroless still shows 0.3.3

- 0.3.7 - https://github.com/bazelbuild/bazel-central-registry/pull/2730
- 0.3.6 - https://github.com/bazelbuild/bazel-central-registry/pull/2575
- 0.3.5 - https://github.com/bazelbuild/bazel-central-registry/pull/2573
- 0.3.4 - https://github.com/bazelbuild/bazel-central-registry/pull/2323

**Comment by thesayyn** [comment]
> Can we close this issue once it's actually released to the registry?

https://registry.bazel.build/modules/rules_distroless/0.3.7
